#!/bin/bash
cd /home/pi
cp /home/pi/Langstone/Langstone.conf /tmp
rm -rf /home/pi/Langstone
git clone https://github.com/Radiomix2000/Langstone.git
/home/pi/Langstone/build
cp /tmp/Langstone.conf /home/pi/Langstone



